# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master
- develop

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.4

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: |
    sudo apt-get install -y build-essential debconf-utils mysql-server
    sudo apt-get install -y unzip xvfb autogen autoconf libtool pkg-config nasm
    sudo service mysql start
    sudo mysql -u root -proot -e 'create database we_music;'
  displayName: 'Installing System Dependencies'

- script: |
    mysql --version
  displayName: 'MySQL Version'

- task: DownloadSecureFile@1
  name: envFile
  displayName: 'Download .env file'
  inputs:
    secureFile: '.env'
    retryCount: '5'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourceDirectory)'
  inputs:
    Contents: |
      .env
    TargetFolder: '$(Build.SourceDirectory)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'Composer Install'

- script: |
    php artisan migrate:fresh --force
    php artisan db:seed --force
  displayName: 'Running Migrations and Database Seeder'